app = "petwitter-api"  


[build]
  builder = "paketo-buildpacks/builder:base" 

[env]
  NODE_ENV = "production" 

[http_service]
  internal_port = 3000  
  force_https = true

[experimental]
  cmd = ["yarn", "start"] 
